apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: schcsaba/kub-dep-feed-api:latest
          volumeMounts:
            - mountPath: "/app/images"
              name: vultr-volume
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongodb_username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongodb_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_secret
      volumes:
        - name: vultr-volume
          persistentVolumeClaim:
            claimName: csi-pvc